### ISSUE TITLE
Please Release Version: 1.1.0

### ISSUE THREAD

**Issue by phillip-kruger** [webjars/graphiql#6]
Seems like the other (NPN / bower)  release process is broken ? I can not seem to get any of them to update.

**Comment by jamesward** [comment]
Maven Central has been having some issues. :( I'll let you know when this is resolved.

**Comment by phillip-kruger** [comment]
Thanks !!

**Comment by jamesward** [comment]
Looks like this should be working better now.

**Comment by phillip-kruger** [comment]
Thanks @jamesward . Is the BinTray sunset going to affect webjars ?

**Comment by jamesward** [comment]
We just need to move to using Maven Central directly: https://github.com/webjars/webjars/issues/1910

**Comment by phillip-kruger** [comment]
Ok cool ! Thanks !
