### ISSUE TITLE
upgrade to 2.2.0

### ISSUE THREAD

**Issue by doogle-oss** [webjars/graphiql#7]
https://github.com/graphql/graphiql/tree/graphiql%402.2.0

**Comment by jamesward** [comment]
Can you use the NPM WebJar for this?  It is much easier to maintain and you can deploy your own releases.  2.2.0 is already available at:
```
"org.webjars.npm" % "graphiql" % "2.2.0"
```

**Comment by doogle-oss** [comment]
I tried to deploy 2.2.0 3rd time and it worked .. guess there was some issue in my first 2 attempt.
